### PR TITLE
SERV_1.2.0

### PR DESCRIPTION
**Pull request by p1gp1g**
Related issue: https://github.com/UnifiedPush/specifications/issues/34

Ping @iNPUTmice

### CODE REVIEW

**Comment by karmanyaahm** [comment]
mb for the delay, so I was thinking, what if we do something more similar to what RFC8030 has?

1. The TTL response from the push server MUST contain an integer between 0 and 4294967296 representing the number of seconds the message will be stored on the server. This MAY be 0 if the push server does not store it.
2. The application server MAY send a TTL header, containing an integer between 0 and 4294967296 representing the number of seconds the message should be stored on the server. The push server SHOULD honor this header the best it can.

**Comment by p1gp1g** [comment]
There are some reason to always use TTL: 0 I've detailed on the related issue. And this is probably the best place to debate.

https://github.com/UnifiedPush/specifications/issues/34#issuecomment-1438065855
> If we do not use `201` + `TTL: 0` then compatibility with webpush can be broken, unless the server handle other webpush spec, at least:
> * Delivery of the push message works like the end-user app acknowledging the message (DELETE /message/push_message_resource)
> * The push server must:
>   * Handle message update
>   * Handle message deletion
>   * Check TTL header
>   
> So I see 2 solutions for UnifiedPush:
> * The push server MUST respond with `201` + `TTL: 0`
> * The push server MUST:
>   * respond with `201` + `TTL: 0`
>   * **OR** Handle message update/deletion and check TTL header (and return TTL <= request TTL )
> 
> *IMO: `201` + `TTL: 0` make the spec easier, and we probably reduce side effect when an application server does not use webpush, like matrix.*

**Comment by iNPUTmice** [comment]
> The TTL response from the push server MUST contain an integer between 0 and 4294967296 representing the number of seconds the message will be stored on the server. This MAY be 0 if the push server does not store it.
> The application server MAY send a TTL header, containing an integer between 0 and 4294967296 representing the number of seconds the message should be stored on the server. The push server SHOULD honor this header the best it can.

That seems to be mostly in line with what I’m describing for [up](https://codeberg.org/iNPUTmice/up).

> There are some reason to always use TTL: 0 I've detailed on the related issue. And this is probably the best place to debate.

When you say always you mean even if the server stores them for longer?

I think this could be left to implementation specific details. For example I've always said that if one wants to support storage one probably also wants to support Topic headers. If a specific implementation decides they don’t want to bother with Topic (or if they are other reasons to pretend the actual TTL is lower then the advertised one then implementations can still return `TTL: 0`

 > Delivery of the push message works like the end-user app acknowledging the message (DELETE /message/push_message_resource)

I don’t think this is relevant for UnifiedPush because the UnifiedPush end user app knows it is using UnifiedPush.

> The push server must:

> Handle message update
> Handle message deletion
> Check TTL header

I actually wasn’t familiar with the fact that an app server can update or delete messages in WebPush but if they can it seems like a sensible thing to require off UnifiedPush as well.

**Comment by p1gp1g** [comment]
> > There are some reason to always use TTL: 0 I've detailed on the related issue. And this is probably the best place to debate.
> 
> When you say always you mean even if the server stores them for longer?

Yes exactly. I see 2 solutions to fit UnifiedPush and Webpush : 
* **(A)** The push server MUST respond with `201` + `TTL: 0`
* **(B)** The push server MUST:
  * respond with `201` + `TTL: 0`
  * **OR** Handle message update/deletion and check TTL header (and return TTL <= request TTL )

ATM, this PR is doing the solution **(A)** (`TTL: 0`, event if the server can store).
But if solution **(B)** is better, then we should edit this PR :)


> I think this could be left to implementation specific details. For example I've always said that if one wants to support storage one probably also wants to support Topic headers. If a specific implementation decides they don’t want to bother with Topic (or if they are other reasons to pretend the actual TTL is lower then the advertised one then implementations can still return `TTL: 0`

So you suggest to follow solution **(B)**. @karmanyaahm too if I understand correctly this message: https://github.com/UnifiedPush/specifications/pull/37#issuecomment-1468301127

---

If we follow solution **(B)**, we need to add spec so push server with `TTL: x`, 0 < x < 4294967296 :
* Handle message update
* Handle message deletion
* Check TTL header

---

> > Delivery of the push message works like the end-user app acknowledging the message (DELETE /message/push_message_resource)
> 
> I don’t think this is relevant for UnifiedPush because the UnifiedPush end user app knows it is using UnifiedPush.

From the webpush spec, an app receiving a message acknowledges the push server with a DELETE request. Then the push server deletes the message. I'm just saying that, with TTL > 0, a successfully pushed message should be considered as an acknowledged message.

**Comment by iNPUTmice** [comment]
Yes I agree with @karmanyaahm and I’m in favor of (B).

I checked the RFC the other day. There is no deletion. And no update per se except the Topic header.

And yes I think we should update the spec to support Topics and TTL. Both are very sensible things to do when it comes to storing messages independently of trying to be compatible with WebPush.

A lot of apps use Push as a pure wake up signal and would use a topic header to collapse those wake up signals. If you don’t support Topic (while supporting storage) your storage might fill up with entirely redundant wake up signals.

**Comment by iNPUTmice** [comment]
> The app server can also send that request before the user-agent receives it: it has the message resource. The spec does not make it crystal clear but it follows the spec to do it.

I’m not reading that from the RFC. The RFC talks about this as a method to acknowledge messages. The verb delete (or retract or remove) does not appear in the normative text and is only used as syntax in the HTTP command. It doesn’t make sense for the app server to acknowledge a message. And a sole delete operation is not specified.

I don’t think we need to allow the app server to delete (not yet delivered) messages in order to be compatible with WebPush. Do we want to allow app servers to delete message regardless? Maybe. I don’t have strong feeling but I’m leaning slightly towards no.

> The push server MUST add a TTL header to its response. The application server MAY ignore it.

Minor nit: What would an application server ignoring the TTL response header look like? Or to frame the question differently: what does an application server do with the TTL header if they are not ignoring it. I’m generally curios. I've regarded the TTL response header as informational; put I don’t think we need to explicitly give the application server the permission to ignore it.

**Comment by p1gp1g** [comment]
> > The app server can also send that request before the user-agent receives it: it has the message resource. The spec does not make it crystal clear but it follows the spec to do it.
> 
> I’m not reading that from the RFC. The RFC talks about this as a method to acknowledge messages. The verb delete (or retract or remove) does not appear in the normative text and is only used as syntax in the HTTP command. It doesn’t make sense for the app server to acknowledge a message. And a sole delete operation is not specified.
> 
> I don’t think we need to allow the app server to delete (not yet delivered) messages in order to be compatible with WebPush. Do we want to allow app servers to delete message regardless? Maybe. I don’t have strong feeling but I’m leaning slightly towards no.

I agree the spec show the deletion only as an ack request from the user agent. But nothing prevent the app server to do it: it has the message resource and the delete request is not authenticated. So, if we want to make UnifiedPush server compatible with webpush it must consider these edge cases.

BTW, all request from my previous comment are from the webpush spec. 

> > The push server MUST add a TTL header to its response. The application server MAY ignore it.
> 
> Minor nit: What would an application server ignoring the TTL response header look like? Or to frame the question differently: what does an application server do with the TTL header if they are not ignoring it. I’m generally curios. I've regarded the TTL response header as informational; put I don’t think we need to explicitly give the application server the permission to ignore it.

An app server not ignoring it may update a message within the TTL receive. For instance a mastodon server could update the notification of an edited post if it has not been received yet. But I'm OK to remove "The application server MAY ignore it" : it is obvious.

---

There is something else that need to be done if TTL > 0 : 


[rfc8030#section-6.3](https://www.rfc-editor.org/rfc/rfc8030#section-6.3)
> The application server requests the delivery of receipts from the
   push service by making an HTTP GET request to the receipt
   subscription resource.  The push service does not respond to this
   request; instead, it uses HTTP/2 server push [[RFC7540](https://www.rfc-editor.org/rfc/rfc7540)] to send push
   receipts when messages are acknowledged ([Section 6.2](https://www.rfc-editor.org/rfc/rfc8030#section-6.2)) by the user
   agent.

We need to look in the webpush spec if there is something else missing

**Comment by karmanyaahm** [comment]
> This TTL header MUST be equal to 0 OR the server MUST support the following requirements:

I agree with this concept. However, I also see @iNPUTmice's train of thought ... do we really need to cover every edge case? The overarching question we need to answer here is - **do we want to be 100% compatible with WebPush (hard, especially w/ ntfy) or is the easy 80% good enough?**

The biggest problem with WebPush is that we have no clue how many apps are even using these advanced features; IMHO we should go slow and handle edge cases as needed. Here's what I suggest:

### Features list

- ✅ TTL - Application server MUST either store it for less than required TTL OR return 0
- 📛 Location endpoint - Always return a random ID path
  - DELETE Location - 404 - we can support it if an app asks for it? (Autopush does supports)
  - GET Location - Acknowledgement/Read Receipts - 404 (Autopush does not support)
- ✅Topic - SHOULD replace message (independent of TTL)
- ❌Urgency - ignore

Although gating features behind `TTL: 0` totally makes sense for compatibility - app servers can't ask for receipts if the message is never stored - I'm afraid it will create a "UnifiedPush-pro" and "UnifiedPush-lite" distinction. The last thing we want is for apps to hard-code such feature distinctions, making them think UnifiedPush is complicated and breaking the experience for future distributors.

**Comment by p1gp1g** [comment]
I think the spec must be webpush compatible. Then the push server implementation may ignore some parts, like autopush does. If an application server has an issue with a push server, the issue will have to be fixed on the push server side.

I wanted to present it in a way we can easily spot fast-forward implementation vs more complex implementation.

With TTL0, many things don't have to be implemented while following webpush specs. If I've missed anything that needs to be implemented even with TTL0, then it should indeed be reworded. (I think it was what you mean with UnifiedPush lite/pro ? Fully webpush compatible or not ?)

**Comment by p1gp1g** [comment]
What do you think of merging the TTL: 0 for SERV_1.2.0 and writing a SERV_1.3.0 that support other webpush features ?

**Comment by p1gp1g** [comment]
Merging TTL:0 in SERV_1.2.0. We will do TTL>0 support later

**Pull request merged**
